### ISSUE TITLE
( missing in your instructions

### ISSUE THREAD

**Issue by student-sx** [chrissound/XMonadLayouts#3]
In your instructions I think there is a `(` missing: 

Instead of 

`layoutHook = desktopLayoutModifiers $ getMiddleColumnSaneDefault 2 0.15 defaultThreeColumn)`

it should be  

`layoutHook = (desktopLayoutModifiers $ getMiddleColumnSaneDefault 2 0.15 defaultThreeColumn)`

**Comment by chrissound** [comment]
Thanks! Feel free to send a PR next time :)
